### ISSUE TITLE
Finished?

### ISSUE THREAD

**Issue by juhaelee** [seatgeek/react-infinite#102]
What's the best way to show that you've reached the end? Should I just replace the loadingSpinnerDelegate to a finished component, and set isInfiniteLoading to true?

**Comment by garetht** [comment]
@juhaelee The recommended way to do it is to set `infiniteLoadingBeginBottomOffset` to `undefined` when the parent component knows that there are no more elements. This will disable infinite loading. If you want to append a special end component you can just include it among the children.

**Comment by juhaelee** [comment]
thanks @garetht !

**Comment by juhaelee** [comment]
@garetht quick question, for the elementHeights, are they the height of the element excluding any margins on the outermost div container?

**Comment by garetht** [comment]
The `elementHeight` is the total height apparent height of the element including all margins, borders, and paddings. If an inner element would be taller than the outermost container, then that height should be used, although this usually shouldn't be the case.
