### ISSUE TITLE
Correct way to use elementHeight on responsive items?

### ISSUE THREAD

**Issue by juhaelee** [seatgeek/react-infinite#106]
So I have a feed item component that's an image and the height of the image changes when I resize my window. I'm wondering what the best approach for this is.

Does react-infinite work if I set the elementHeight for the image to be the minimum height? Say the smallest height the image can get is 100px, but on desktop its 600px. If I use element height [100, 100] would that be ok?

Or...

Should I use a debouncer on window.resize, and just reset the element heights using setState?

**Comment by garetht** [comment]
Minimum heights are unlikely to work acceptably. Feeding a new list of element heights on resize at breakpoints would be the current optimal solution.

**Comment by vgoklani** [comment]
How do you properly calculate the element heights? The text *wraps* around, which makes it very tricky... I have all sorts of "heuristics", but I tend to be wrong ~5% of the time. Please see attached screenshot:

https://www.dropbox.com/s/gbfs1rthqw807ha/Screenshot%202015-11-12%2012.05.25.png?dl=0

**Comment by garetht** [comment]
I don't believe there is a way without DOM measurements, which have not yet been implemented.
