### ISSUE TITLE
Issue when hitting the end.

### ISSUE THREAD

**Issue by rdlin** [seatgeek/react-infinite#11]
Hello,
I am having an issue where I cannot seem to handle hitting the end of the elements very well. I am hitting a backend api where there is a large but limited number of results. What is the best way to do this?
Thanks!

**Comment by garetht** [comment]
Hi,

Could you describe in more detail the problem you face when hitting the
end? If you could provide some example code that would be great as well.

**Comment by rdlin** [comment]
I was able to solve my issue. Basically when my api call returned no results I called setState within my handleInfiniteLoad for the old elements. Not called this at solved the errors I was getting. Do you have any tips as to how I could possibly modify this to work for variable sized elements? Thank you

**Comment by garetht** [comment]
@rdlin Variable heights are now supported by passing in an array of the children elements' heights.

Here is an example:
```
<Infinite containerHeight={200} elementHeight={[111, 252, 143]}>
    <div className="111-px"/>
    <div className="252-px"/>
    <div className="143-px"/>
</Infinite>
```

Let me know if you have questions.

**Comment by rdlin** [comment]
Thanks for the update. This is awesome.
