### ISSUE TITLE
Not able to scroll to the last item 

### ISSUE THREAD

**Issue by ruchigoyal2005** [seatgeek/react-infinite#112]
I have a expandable list inside the react-infinite wrapper. I am not able to scroll to the last item when I expand items in my list. Do I need to recalculate height and increase the content height after I expand items? is yes then how should I increase the content height? is there any props to do that?

**Comment by garetht** [comment]
@ruchigoyal2005 Yes, you do. The `elementHeight` prop can be a list of element heights. So suppose you start with `[100, 100, 100]`. When the second element expands by 200 pixels, the parent element should pass in `elementHeight`s of `[100, 300, 100]` instead.

**Comment by ruchigoyal2005** [comment]
@garetht : what happens when content wrap? is there anyway to calculate the height that time?

**Comment by garetht** [comment]
That is part of https://github.com/seatgeek/react-infinite/issues/61, although the continual changes may be more challenging than what that issue initially envisioned.
