### ISSUE TITLE
useWindowAsScrollContainer does not work with Internet Explorer

### ISSUE THREAD

**Issue by zpratt** [seatgeek/react-infinite#114]
I'm using `useWindowAsScrollContainer={true}` and I've run into a serious issue with Internet Explorer (I've tested with IE 11). What happens is that once the component goes to render the children I've passed to it (when the array of children has at least 1 element), the page locks. I cannot say exactly what the issue is yet, but I have isolated the initial root of the issue to here: https://github.com/seatgeek/react-infinite/blob/9ade2b50ffcb5d3f782f53cf0c0e1b8fd561a837/src/react-infinite.jsx#L119

If I change:
```
newProps.containerHeight = props.useWindowAsScrollContainer
      ? window.innerHeight : containerHeight;
```
to
```
newProps.containerHeight = containerHeight;
```

then the problem goes away. Obviously that's not a solution since the page does not render correctly without this. I'm not sure of the exact issue, I'm just trying to share what I was able to find while debugging.

**Comment by zpratt** [comment]
I should also add that I'm using v0.6 since I am currently stuck on React 0.13 for the near future.

**Comment by zpratt** [comment]
I've put together a fiddle that uses react 0.14 and the latest version of react-infinite to illustrate the issue exists in the latest supported version. [Here's the link](//jsfiddle.net/fxh4wd6h/embedded/result/) with the issue. [Here's a link](//jsfiddle.net/zpratt/p42w9ajo/embedded/result/) without the issue.

**Comment by sarmadsangi** [comment]
@zpratt 
I actually ran into this exact issue with IE 11, in my case i debugged and found out that `window.scrollY` is not supported by IE 11 (only by IE edge). When you set `useWindowAsScrollContainer ` infinite-scroll starts using  `window.scrollY`. This should fix it for ie11

https://github.com/seatgeek/react-infinite/pull/115

**Comment by zpratt** [comment]
@sarmadsangi i have tested this in my project and it definitely fixes the issue. i've also tested the change in chrome and firefox and i didn't see any issues. 

according to the [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset) the scrollY/scrollX and pageYOffset/PageXOffset window properties are aliases. it just looks like IE chose not to implement the alias until Edge.

**Comment by garetht** [comment]
@zpratt @sarmadsangi Just released a new version that should fix this, thanks for the report and contributions!
