### ISSUE TITLE
When the container is too large, not all rows are loaded

### ISSUE THREAD

**Issue by AlanFoster** [seatgeek/react-infinite#118]
When the container is larger than the height of all loaded rows `onComponentMount`, the remaining rows  are not requested after the first request is made to `onInfiniteLoad`.

Scenario:
The user's `onInfiniteLoad` implementation returns 10 rows at a time, but the initial height expands to the user's browser height. Therefore on larger monitors we may be able to fit 100 rows at once. Therefore we should make further requests to `onInfiniteLoad`

**Comment by garetht** [comment]
@AlanFoster thanks for the contribution! I've just released 0.8.0 with your fix.
