### ISSUE TITLE
window.innerHeight=0

### ISSUE THREAD

**Issue by EvynXu** [seatgeek/react-infinite#127]
I use your library on Android devices. UseWindowAsScrollContainer={true}. But in the render window.innerHeight=0; I need in componentDidMount and setTimeout to delay load data, to ensure window.innerHeight has the value of, excuse me, there is no other solution

**Comment by garetht** [comment]
The render of React Infinite can be delayed until the conditions you require are met.

**Comment by EvynXu** [comment]
ok
