### ISSUE TITLE
Custom trigger, non-automatic.

### ISSUE THREAD

**Issue by jackyon** [seatgeek/react-infinite#142]
hi~

is there any method to trigger the next page loading manually?

i.e click one button then start to load the next page of the contents.
http://www.infinite-scroll.com/trigger.html

plz advise.
thx.

**Comment by garetht** [comment]
You should be able to do that by making the loading spinner a button using the [`loadingSpinnerDelegate`](https://github.com/seatgeek/react-infinite#react-node-loadingspinnerdelegate) , and then have an `onClick` handler on the parent component that contains React Infinite. The handler will feeds new data to Infinite only when clicked, allowing manual scrolling to be implemented.
