### ISSUE TITLE
React v15.0.0-rc1

### ISSUE THREAD

**Issue by geekyme** [seatgeek/react-infinite#145]
Hello, React v15 is out, would love to use this library for my build too but your peerDependencies are declaring v0.14.

https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html

**Comment by garetht** [comment]
Now available in 0.9.

**Comment by geekyme** [comment]
@garetht is it better to declare package.json's react dependency as `^15.0.0-rc1` ? this way NPM won't complain if react updates to 15.1.0 etc

**Comment by garetht** [comment]
No. This causes problems in much older versions of NPM, and so will be kept until `15.0.0` is released.

**Comment by geekyme** [comment]
I see. Got it! Thanks for the clarification!
