### ISSUE TITLE
How do you stop the infinite spinner after reaching the last item?

### ISSUE THREAD

**Issue by akhayoon** [seatgeek/react-infinite#151]
Great addon, I wanted to know if there was an easy way of stop the infinite spinner from showing when I reach the last element in my array. 

I'm playing with trying to keep the isInfiniteLoading property to false when I reach the end of my list, but I wanted to see if there was a right way to do this.

**Comment by akhayoon** [comment]
one way I achieved this was by setting infiniteLoadBeginEdgeOffset to undefined when newElements length is 0 inside the handleInfiniteLoad method

**Comment by garetht** [comment]
Yup, that is the correct way to do it.
