### ISSUE TITLE
use parent's height as containerHeight

### ISSUE THREAD

**Issue by IanWang** [seatgeek/react-infinite#156]
I think it would be great that we don't need to specify the pixel as a prop

instead, if there's one, just use parent's height as the default containerHeight

what do you think?

I'd like to send a pr for this

**Comment by garetht** [comment]
React Infinite does not currently measure any heights through the DOM, but I think it would be easy to write a wrapper component that measures the height of the parent and then provides it to React Infinite as a default so that React Infinite can continue to work without height measurements.

**Comment by mjrussell** [comment]
I currently use [react-dimensions](https://github.com/digidem/react-dimensions) as a wrapper to pass it down and it works quite well. Only downside is yet another extra div

**Comment by IanWang** [comment]
@garetht @mjrussell Actually I do use a wrapper to measure the height of the parent and pass it down to React Infinite. My question here is instead of throw an error when containerHeight is not provided, why not use parent as the container (or a new props `useParentAsScrollContainer`)? 

Sure a simple wrapper can solve this but if this scenario we talk about here is really common, why not make it part of this package?

**Comment by garetht** [comment]
We are trying to limit the extent of the reliance of React Infinite upon the DOM. The window measurements were thrown in there because of the way window scroll listeners work, but any further DOM measurements seem to me to be the job of other components. It would make sense to include these helper wrappers in the future in the NPM package.

**Comment by suheb** [comment]
@mjrussell Can you provide some code of how you do this with react-dimensions? Would really appreciate it. Thanks.

**Comment by mjrussell** [comment]
@suheb sure, the `...` just mean more stuff in this case, not ES6 spread operator.
```js
@Dimensions()
export default class MyComponent extends Component {
  static propTypes = { 
    containerHeight: PropTypes.number.isRequired,
  }

  render() {
    return (
      <Infinite containerHeight={this.props.containerHeight} ... >
        ....
      </Infinite>
  }
}
```

Or if you aren't using ES7 decorator syntax:
```js
export default Dimensions()(MyComponent) 
```
