### ISSUE TITLE
Scrolling issues when an element wraps objects

### ISSUE THREAD

**Issue by RamonBeast** [seatgeek/react-infinite#158]
I'm using the sample code proposed in #135 with redux, now everything works smoothly with the following code:

```
<Infinite elementHeight={41}
               containerHeight={400}
               infiniteLoadBeginEdgeOffset={140}
               onInfiniteLoad={this.handleInfiniteLoad}
               isInfiniteLoading={this.state.isInfiniteLoading}
               timeScrollStateLastsForAfterUserScrolls={1000}
      > 
       {this.state.elements}
    </Infinite>
```

What I would like to do is to load a series of accordion items that are expandable, like this:

```
<Infinite elementHeight={41}
               containerHeight={400}
               infiniteLoadBeginEdgeOffset={140}
               onInfiniteLoad={this.handleInfiniteLoad}
               isInfiniteLoading={this.state.isInfiniteLoading}
               timeScrollStateLastsForAfterUserScrolls={1000}
      >
      <Accordion>
        {this.state.elements}
      </Accordion>
    </Infinite>
```

Everything works fine until the first set of elements is loaded, after that new elements are correctly fetched from the server but the scroll doesn't work anymore and simply reloads the view on the first X elements shown. To reproduce the issue is sufficient to add a `div` before the elements:

```
<Infinite elementHeight={41}
               containerHeight={400}
               infiniteLoadBeginEdgeOffset={140}
               onInfiniteLoad={this.handleInfiniteLoad}
               isInfiniteLoading={this.state.isInfiniteLoading}
               timeScrollStateLastsForAfterUserScrolls={1000}
      >
      <div>
        {this.state.elements}
      </div>
    </Infinite>
```

The inner div, or whatever element is added, disturbs the scroll. What happens is that after loading the new set of elements, there's a div element generated by react-infinite that grows exponentially. Initially it's like this:

![Initial state](http://i.imgur.com/AbNDS3Q.png)

And after 2-3 scrolls it becomes huge (check the `height` attribute):

![After scrolling](http://i.imgur.com/cC0Q3BE.png)

Apparently this doesn't happen if the inner div is removed (or in my case the accordion component). Is there any way to use another element inside `<Infinite />` without messing up with the scrolling?

**Comment by RamonBeast** [comment]
@garetht given your experience on this project and contributions, do you have any suggestion for this use case? Thank you in advance for any help.

**Comment by Evilcry** [comment]
I’m having similar issues with my project and I was wondering if there is a solution.

**Comment by garetht** [comment]
The behavior is expected because the API is being used incorrectly. The scrollable elements must be at the top level. It is not possible to use wrapped elements both because React Infinite is unaware of the output of the wrapper and because it cannot assume that the wrapped element's output can be arbitrarily manipulated.
