### ISSUE TITLE
Fix infinite load offset in window-scroll mode #When would be merged fix into master?....

### ISSUE THREAD

**Issue by yevhen-hryhorevskyi** [seatgeek/react-infinite#165]
Hi.
I was looking for react plugin to handle infinity scroll in a nice way and I liked react-infinite. 
Unfortunately, I tried to set up infinity scroll to the window and it's not working. 

After fast investigation have found https://github.com/seatgeek/react-infinite/pull/136/commits/0f9ee33c624c11b795b6486ae9b632459d384f5c pull request which could fixed my issue, but hasn't been merged to master yet.. 

Can you say approximately when this fix will be included to master version and will available in nmp repo?

**Comment by diabolicfutility** [comment]
Infinite loading works with the window as the scroll-container, the issue is that it miscalculates some stuff. Play around with the value you pass to infiniteLoadBeginEdgeOffset and it should work, I wanted it to trigger at 300 pixels from the bottom, and passing in -100 does that for me.

**Comment by garetht** [comment]
@EugeneGrigorevskiy Do you have a reproduction of the bug?
