### ISSUE TITLE
List flickers

### ISSUE THREAD

**Issue by jamesfzhang** [seatgeek/react-infinite#166]
This only happens occasionally. So far I've been able to reproduce it on Chrome 50. This happens in the "Hot right now" section of https://theartistunion.com.

That section is implemented with this `List`.

```jsx
<List
  fetching={false}
  canFetch={false}
  itemHeight={93}
  title={this.renderTitle()}
  items={this.state.trendingTracks}
  renderItem={this.renderItem}/>
```

Which is a component I wrote that wraps around `Infinite`.

```jsx
render: function() {
  return (
    <article>
      {this.renderTitle()}
      <Infinite
        infiniteLoadBeginEdgeOffset={60}
        useWindowAsScrollContainer={true}
        elementHeight={this.props.itemHeight}
        isInfiniteLoading={this.props.canFetch && this.props.fetching}
        onInfiniteLoad={_.debounce(this.handleFetch, 2000, true)}
        loadingSpinnerDelegate={this.renderLoading()}>
        {this.renderItems()}
      </Infinite>
    </article>
  );
},

handleFetch: function() {
  if (this.props.canFetch && !this.props.fetching && this.props.handleFetch) {
    this.props.handleFetch();
  }
}
```

This list of songs is static and does not use the infinite loading feature of this component. Why does it flicker though? Thanks!

![flicker](https://cloud.githubusercontent.com/assets/2057670/15561764/0a7204bc-22ae-11e6-82d7-1fdc14d67469.gif)

**Comment by taylorjames** [comment]
Inspecting the list items on your website I see that each element is 100px in height, not 93px as stated in your code above. In order for this component to work properly you need to provide the exact height of each list item. The height lets the absolute scrolling know which elements should be in the viewport, if the height is off,  the scrolling starts to "jump" to correct the difference between the actual height and the height prop.

Try this:
```<List
  fetching={false}
  canFetch={false}
  itemHeight={100}
  title={this.renderTitle()}
  items={this.state.trendingTracks}
  renderItem={this.renderItem}/>```

**Comment by jamesfzhang** [comment]
Thanks @taylorjames that fixed it.
