### ISSUE TITLE
undetermined scroll container height

### ISSUE THREAD

**Issue by vqng** [seatgeek/react-infinite#170]
I have a HTML structure like this:

```
div.parent
  div.username
  div.images
  div.react-infinite-container
```

can I set `containerHeight` to "auto expanding" instead of a fixed height? By auto expanding, I mean making the infinite scroll container takes as much remaining height as possible in parent.

**Comment by aymericbouzy** [comment]
I would be interested in this feature too : being able to set `flex: 1` on the scroll container would do it for me.

**Comment by richardlopes-daitangroup** [comment]
Any news on this?

**Comment by aymericbouzy** [comment]
Have you tried react-virtualized? It's powerful too
