### ISSUE TITLE
Not worked with React 15.3.1 

### ISSUE THREAD

**Issue by Porshe** [seatgeek/react-infinite#186]
Not worked with React 15.3.1 

![2016-08-22 13-31-45](https://cloud.githubusercontent.com/assets/4263573/17851865/d4fe0704-686c-11e6-9143-4a413402806e.png)

**Comment by thaggie** [comment]
I've created a pull request that should fix this:
https://github.com/seatgeek/react-infinite/pull/188

**Comment by garetht** [comment]
This should be fixed in 0.10.0.
