### ISSUE TITLE
Flow type dependency errors

### ISSUE THREAD

**Issue by volkanunsal** [seatgeek/react-infinite#187]
I just installed this project and got this error:

```
node_modules/react-infinite/src/react-infinite.jsx:175
175:   generateComputedUtilityFunctions(props: ReactInfiniteProps): ReactInfiniteUtilityFunctions {
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ identifier `ReactInfiniteUtilityFunctions`. Could not resolve name
```

I imagine you could fix this by importing the `react_inifinite_types` from the base type definition file.

**Comment by volkanunsal** [comment]
I fixed this in my project by adding the flow definition files into my `.flowconfig`. But it would be cool if the type definitions used the [`.js.flow` style](https://flowtype.org/docs/declarations.html#declaration-files), so this wasn't necessary.

**Comment by Bnaya** [comment]
@volkanunsal I'm having the same issue, can you share the definition you've added?
Thanks!

**Comment by Bnaya** [comment]
``
[libs]
node_modules/react-infinite/typelib
``
Got this, thanks!
