### ISSUE TITLE
Performance issue when rendering complex rows

### ISSUE THREAD

**Issue by aymericbouzy** [seatgeek/react-infinite#190]
I have a list with 2000 rows. My issue is that each row takes some time to render (about 1ms). When I need to rerender my whole list (because something in the state changed such that each row needs to rerender), there are frame drops. 

My suggestion would be to provide a renderRow prop such that ReactInfinite knows how to render each row, and provide the rows as an array, each element being provided as argument to renderRow when it needs to be rendered. That way, ReactInfinite would be able to rerender only the rows that are currently displayed when the state changes and not all 2000 rows.

I can provide more information if needed.

**Comment by syndbg** [comment]
@aymericbouzy I think https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md is more appropriate for your use case.

**Comment by aymericbouzy** [comment]
Thanks a lot ! haven't tested yet, but it looks a lot like what I've been looking for. I've been searching everywhere on the web for this kind of library. I hope it gets more popular and gains visibility ! Thanks again.
