### ISSUE TITLE
can not use this component with table

### ISSUE THREAD

**Issue by TranQuocViet** [seatgeek/react-infinite#208]
I am facing a problem with this component, i can not use it together table, in my case, i use  it to load data into a ["react-semantic table"](http://react.semantic-ui.com/collections/table) but it don't work look like my hope, when i scroll reach to` infiniteLoadBeginEdgeOffset` it auto continue scroll endless to endless. How i can use table together it, point me please ! Thank

**Comment by vitnguyhiem** [comment]
I have a same issue

**Comment by ericdvb** [comment]
Just posted a possible solution in https://github.com/seatgeek/react-infinite/issues/220 - I think these are the same issue. Does that solution work for you?

**Comment by TranQuocViet** [comment]
I think need create a tab by div tag to work with react-infinite. I did that
