### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by Sharlaan** [seatgeek/react-infinite#215]
Still using React.createClass() when it will [soon get deprecated](https://facebook.github.io/react/blog/#migrating-from-react.createclass).

Missing lot of ES6 features when we are already in ES7 era.

Last commit from Oct2016...

**Comment by garetht** [comment]
You should feel welcome to submit pull requests for features you'd like!

**Comment by sesteva** [comment]
@garetht there are 15 PRs all the way back to 2015. How can we help?
