### ISSUE TITLE
React.PropTypes is deprecated

### ISSUE THREAD

**Issue by serut** [seatgeek/react-infinite#221]
When we use your package, we can see this line in the browser console while developing :  

`Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

It looks like there is 2 files containing these imports : 

- https://github.com/seatgeek/react-infinite/blob/master/src/react-infinite.jsx#L15-L56
- https://github.com/seatgeek/react-infinite/blob/master/src/utils/types.js#L4-L10

Just execute the following `npm i --save-dev prop-types` & replace all `React.PropTypes` into `PropTypes` and you're good.

**Comment by garetht** [comment]
Fixed in 0.11
