### ISSUE TITLE
DIV inside containerElement just grows in height

### ISSUE THREAD

**Issue by SmboBeast** [seatgeek/react-infinite#225]
I'm not sure if I'm doing anything wrong here, but a random div element that is added inside my containerElement just keeps growing in height.  This happens when scrolling and when not scrolling.

Below is my code, and underneath is a snapshot of what I'm talking about.  That height number just goes until infinity.  Any idea?  Kind of crazy.  The elements inside of the Infinity component vary in height greatly.  Although they are all 180px tall, they are grouped together by date, so really putting a number on it is tricky.

```
<Infinite containerHeight={400} elementHeight={180} infiniteLoadBeginEdgeOffset={100} onInfiniteLoad={this.handleInfiniteLoad} isInfiniteLoading={this.state.isInfiniteLoading}> 
MY ELEMENT 
</Infinite>
```

![screen shot 2017-06-05 at 6 28 12 pm](https://cloud.githubusercontent.com/assets/287007/26809955/6cdcf37c-4a1d-11e7-837c-d03ae6812666.png)

**Comment by amccloud** [comment]
@SmboBeast what ended up being the problem here?
