### ISSUE TITLE
How to calculate each element (NOT container) height

### ISSUE THREAD

**Issue by SmboBeast** [seatgeek/react-infinite#226]
I have gone through the docs and everything else I can find (examples + other people reporting similar problems), but I can't find a solution for this anywhere.  I have seen some react-measure solutions, but that measures the containerHeight.  I need one level down, to figure out the elementHeights.

How are we supposed to calculate the different element's heights exactly?  I have a case where I have variable heights because the inner element lists are complex and are nested.  I basically have  grouped divs (containers) by date, which house unordered lists of images.

Any help is appreciated.

Thanks

**Comment by cdimitroulas** [comment]
I second this issue, it seems as though this library cannot be used with elements of unknown heights. I would like to use this for a chat infinite scroll but messages can be of variable heights therefore it makes it very difficult to use this as a solution

**Comment by SmboBeast** [comment]
@cdimitroulas 

You're correct here.  This library doesn't deal with variable element heights.  There are said to be some additional libraries you can use that are supposed to help with this, but honestly, none of them work for me.  Their demos are even problematic for me.  You can find them if you look through the Issues others have reported.

However, you can take a look at this here: https://github.com/seatgeek/react-infinite/issues/220 to see the workaround I came up with.  Works fine for me now.

Sam 
#220

**Comment by dkonayuki** [comment]
The workaround is not an ideal solution.
Someone please consider this as an improvement of react-infinite.
