### ISSUE TITLE
Flaky onclick

### ISSUE THREAD

**Issue by 8enmann** [seatgeek/react-infinite#246]
### What happens
When scrolling fast, when I stop, list item click events don't register on the first click or first couple of clicks 
### What I expect to happen
Click events are passed to children appropriately

### Steps to reproduce
1. `git clone git@github.com:8enmann/scroll-demo.git`
1. `npm install && npm start`
1. Open console and click an item. Scroll quickly and then click an item. Sometimes there's no console log on the first click.

**Comment by garetht** [comment]
This is deliberate by default in order to improve the user experience on certain platforms with inertial scrolling. You should be able to turn it off by setting [this prop](https://github.com/seatgeek/react-infinite#number-timescrollstatelastsforafteruserscrolls) to 0.

**Comment by 8enmann** [comment]
Seems to work. Thanks!
