### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Oleksander-Derechei** [seatgeek/react-infinite#251]
Hi, I am using react-infinite, and during `npm i` I get:

> react-infinite@0.12.1 requires a peer of react@^15.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-infinite@0.12.1 requires a peer of react-dom@^15.5.0 but none is installed. You must install peer dependencies yourself.

Current react version is 16.

Please, update  dependencies.

**Comment by kgregory** [comment]
This is a duplicate of #247 and there is a PR pending for this, see #240

cc: @garetht

**Comment by garetht** [comment]
This has been released as 0.13.0.
