### ISSUE TITLE
Request to change license to standard flexible open source

### ISSUE THREAD

**Issue by bryans99** [seatgeek/react-infinite#280]
I'd like to use it for a project but my management is very strict about the licenses that we can use.  They have asked me to reach out to you to see if you are amenable to changing it to a flexible open source license such as MIT or Apache 2.0 (not GPL). As an aside, we are also looking at react-infinite-any-height which wraps react-infinite. It has been released under the MIT license.

Many thanks for your consideration.

**Comment by garetht** [comment]
Just forwarded this request along to our legal department.

**Comment by garetht** [comment]
Unfortunately, they aren't in favor of the idea, but have noted that the current license is `just as permissive as MIT`.
