### ISSUE TITLE
Window as the container

### ISSUE THREAD

**Issue by srph** [seatgeek/react-infinite#29]
I haven't tried out the library, but would like to. However, I haven't seen an example of having the `window` as the `container`. Would this be correct?

```jx=sx
<InfiniteScroll containerHeight={window.innerHeight}>
  ...
</InfiniteScroll>
```

**Comment by cmwelsh** [comment]
I also want to use the window as the container. It seems like there are some style attributes e.g. `overflow` that are applied to the container so this is not a supported use case...

**Comment by garetht** [comment]
Hmm I think it should be possible to use an that occupies all the space in the window, but I haven't tried it. I'll look into it and see if I can make an example if it's possible.

**Comment by srph** [comment]
Ah, thanks for the response!

@garetht Would look forward to that, if it's possible :smile:

**Comment by garetht** [comment]
@srph I've included an example of how to use the window as a container [here](https://github.com/seatgeek/react-infinite/blob/master/examples/window.html).

Result:

![](http://cl.ly/image/292y2y0F2L2X/Screen%20Shot%202015-06-03%20at%203.54.44%20PM.png)

**Comment by srph** [comment]
Wow, @garetht!
