### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by travisperson** [seatgeek/react-infinite#34]
Has anyone used this with webpack? I've trying to find a loader that will work to transform the es6, and so far I've found https://github.com/babel/babel-loader, but haven't gotten it to work completely.

**Comment by disusered** [comment]
I've had luck using the built version. Webpack will warn about it, but it'll work:

`var ReactInfinite = require('react-infinite/dist/react-infinite');`

**Comment by travisperson** [comment]
Awesome thanks! I haven't had time to try this yet, but I'll see if I can sit down today.

**Comment by droberts84** [comment]
I was able get webpack to load from the source with the following in my webpack config file

    var rootPath = path.join(__dirname, '../')
    config.module = {
      loaders: [
        // my other loaders are here..
        // need to load all react-infinte modules via babel
        { test: /\.js$/, include: path.join(rootPath, 'node_modules', 'react-infinite'), loader: 'babel-loader' },
      ],
    };

Make sure `rootPath` is set to to the appropriate path that contains your `node-modules` directory.

**Comment by garetht** [comment]
This should be fixed in 0.4.0. A /build folder is now available with compiled CommonJS code that should be used by Webpack.
