### ISSUE TITLE
reactify should be a dependency

### ISSUE THREAD

**Issue by tmcw** [seatgeek/react-infinite#38]
Browserify transforms should be dependences rather than devDependencies so that they don't have to be installed by the parent module

**Comment by cmwelsh** [comment]
I think the best way right now for the ecosystem is to compile to ES5 before publishing to npm.

**Comment by garetht** [comment]
I'll look into this and the other packaging-related issues next week.

**Comment by garetht** [comment]
This should be fixed in 0.4.0. A `/build` folder is now available with compiled CommonJS code that should be used by Browserify.
