### ISSUE TITLE
Type Error 

### ISSUE THREAD

**Issue by asvsfs** [seatgeek/react-infinite#4]
Hi , 

On my first try using react-infinite i got runtime type error : 

""
TypeError: ({_owner:{props:{data:[]}, _owner:{props:{}, _owner:{props:{}, _owner:null, _lifeCycleState:"MOUNTED", _pendingProps:null, _pendingCallbacks:null, _pendingOwner:null, refs:{}, state:null, _pendingState:null, context:null, _currentContext:{}, _pendingContext:null, _descriptor:{__realComponentInstance:{}}, _compositeLifeCycleState:null, _rootNodeID:".0", _mountDepth:0, _defaultProps:null, getDOMNode:(function () {
"use strict";

      return method.apply(component, arguments);
    }), _pendingForceUpdate:false, _renderedComponent:{}}, _lifeCycleState:"MOUNTED", _pendingProps:null, _pendingCallbacks:null, _pendingOwner:{props:{}, _owner:null, _lifeCycleState:"MOUNTED", _pendingProps:null, _pendingCallbacks:null, _pendingOwner:null, refs:{}, state:null, _pendingState:null, context:null, _currentContext:{}, _pendingContext:null, _descriptor:{__realComponentInstance:{}}, _compositeLifeCycleState:null, _rootNodeID:".0", _mountDepth:0, _defaultProps:null, getDOMNode:(function () {
"
""
same with the example.

**Comment by garetht** [comment]
What version of React are you using?

**Comment by asvsfs** [comment]
0.12.2

**Comment by garetht** [comment]
Since this issue was created React Infinite has been tested to work with 0.12.2. Let me know if this is still an issue.
