### ISSUE TITLE
Allow customization of containing element.

### ISSUE THREAD

**Issue by jacobb** [seatgeek/react-infinite#45]
I'd love to use this easily for infinite scrolling a table, where the child element would be a tbody (with some thead above it). Does this sound feasible as an addition? I'd be happy to submit a PR to get it in.

**Comment by dropfen** [comment]
can't you just put the table rows as childs?

**Comment by jacobb** [comment]
It is my understanding that that is not valid HTML: divs (and other block level tags) are allowed within a td, but not in between the table and td. Using them as childrens would produce something like:


<table>
  <thead>...</thead>
  <tbody>
   <div {react-infinte code here}>
     <tr {child 1}>
      <td>...</td>
      <td>...</td>
    </tr>
     <tr {child 2}>
      <td>...</td>
      <td>...</td>
    </tr>
  </div>
</table>

Which is not valid HTML.

**Comment by dropfen** [comment]
Aaa, you are right, forgot the infinite wrapper.. yep

**Comment by dropfen** [comment]
you need to extend the infinite div to a tbody tag.. in my understanding it should do the thing

**Comment by garetht** [comment]
I don't think support for `<table>`s will be forthcoming because they dictate a certain DOM structure that isn't easily hacked around for this project.
