### ISSUE TITLE
Browser scroll

### ISSUE THREAD

**Issue by alolis** [seatgeek/react-infinite#46]
Hello,

I was wondering if it's possible to have a container that uses the scroll bar of the browser instead of it's own, without necessarily to be a full window container.

Thanks for your time

**Comment by bigappleinsider** [comment]
+1 I am interested in this feature. @alolis Did you get a reply for your question? cc: @garetht

**Comment by garetht** [comment]
@bigappleinsider Do you have an example of a page that has a feature like this?

**Comment by bigappleinsider** [comment]
@garetht Yeah, but it's currently implemented in Angular JS - article feed - http://www.complex.com

**Comment by alolis** [comment]
@bigappleinsider , there seems to be an example [here](https://github.com/seatgeek/react-infinite/tree/master/examples)

**Comment by bigappleinsider** [comment]
@alolis I tested both examples. Both of them add a scrollbar when feed is embedded on a page. I may need to get it working without a plugin. It's ok
