### ISSUE TITLE
element with different height

### ISSUE THREAD

**Issue by trungpham** [seatgeek/react-infinite#5]
what will happen if the elements don't have the same height?

**Comment by trungpham** [comment]
it doesn't seem to work with variable element height.

This project seems to do the same thing but it supports variable height: https://github.com/orgsync/react-list

**Comment by garetht** [comment]
Variable heights aren't supported yet.

**Comment by trungpham** [comment]
@garetht It turns out that the other scroll list doesn't support variable height either. I'm beginning to think that this is not mathematic possible.

**Comment by garetht** [comment]
@trungpham would you be able to know the heights of the elements at the time that you pass them in?

**Comment by trungpham** [comment]
Not always as the height can change when the user resizes the window.

**Comment by garetht** [comment]
@trungpham Variable heights are now supported by passing in an array of the children elements' heights. To make this work for when a user resizes the window, you can set up an event listener to compute and pass in a different array of element heights on window resize.

Here is an example:
```
<Infinite containerHeight={200} elementHeight={[111, 252, 143]}>
    <div className="111-px"/>
    <div className="252-px"/>
    <div className="143-px"/>
</Infinite>
```

Let me know if you have questions.

**Comment by trungpham** [comment]
thanks.

**Comment by Radivarig** [comment]
@trungpham if you're still looking for variable height, you can use this react-infinite wrapper, [react-infinite-any-height](https://github.com/Radivarig/react-infinite-any-height)
