### ISSUE TITLE
support reverse infinite scroll like a chat app

### ISSUE THREAD

**Issue by dustingetz** [seatgeek/react-infinite#54]
Seems straightforward enough to implement, any objections? I'm going to add a boolean prop `reverse`, and a few if statements, any other ideas for a better implementation?

**Comment by garetht** [comment]
@dustingetz sounds good to me.

**Comment by dustingetz** [comment]
I took a whack at this and have it working, except, the scroll position jumps a small amount when loading backwards. [Here is the changeset](https://github.com/seatgeek/react-infinite/compare/master...dustingetz:master). Set `reverse=true` for all three <Infinite/>'s in examples/index.jsx, scroll up and see I wasn't able to make the scroll position quite right. Maybe it would be really obvious to you how to fix this remaining issue? I'd appreciate it if you could take a look.

**Comment by dustingetz** [comment]
Better link to the changeset: https://github.com/seatgeek/react-infinite/compare/master...dustingetz:master#diff-399d170217a64764424dff05d9d27d4f

**Comment by TrkiSF2** [comment]
@dustingetz I am just looking for a way to implement react-infinite in a reverse way. When do u think this could be implemented?

**Comment by szymonmichalak** [comment]
+1

**Comment by TrkiSF2** [comment]
@dustingetz @szymonmichalak any progress?

**Comment by dustingetz** [comment]
I have released an alpha version of my rewrite to NPM, it is rebranded as react-chatview and available here https://github.com/dustingetz/react-chatview

Branding subject to change, everything subject to change, you shouldn't use it :D

Mostly just posting it here because I can't find a way to contact @garetht directly (hi @garetht , you forked an old version this week, this is the latest)

**Comment by garetht** [comment]
@dustingetz Thanks for letting me know, just sent you an email.

**Comment by garetht** [comment]
This has just been implemented, and can be enabled [with the `displayBottomUpwards` prop](https://github.com/seatgeek/react-infinite#bool-displaybottomupwards).

A (contrived) example is available [here](https://github.com/seatgeek/react-infinite/blob/master/examples/chat.jsx).
