### ISSUE TITLE
Get initial elements from onInfiniteLoad

### ISSUE THREAD

**Issue by aop** [seatgeek/react-infinite#57]
Why does this require initial elements in the state before first rendering?
Wouldn't it be a lot better if building the Infinite, it would first time trigger the loading of elements. This would reduce complexity required to load elements multiple ways and displaying the normal loading elements even while loading the first elements?

**Comment by chandu0101** [comment]
interesting :+1:

**Comment by garetht** [comment]
This could probably go in with https://github.com/seatgeek/react-infinite/issues/39.
