### ISSUE TITLE
Binary Search for variable height list item do not handle empty array case

### ISSUE THREAD

**Issue by jimmykobe1171** [seatgeek/react-infinite#59]
the binary search function `binaryIndexSearch(array, item, opt)` will return `undefined` when the input array is empty, which lately will trigger the return of function `getDisplayIndexEnd` to be `NaN`.

Best,
Jimmy

**Comment by ahutchings** [comment]
Does this still occur with 0.4.1? That integrated #48 which handles a couple of cases that would have resulted in NaN.

**Comment by jimmykobe1171** [comment]
Oh, I installed through npm, which is version 0.3.4.

**Comment by jimmykobe1171** [comment]
I just have a look at the latest version on Github, the function `getDisplayIndexStart` seems still not handle the `undefined` case when `this.prefixHeightData` is empty array.

```
getDisplayIndexStart(windowTop) {
    return bs.binaryIndexSearch(this.prefixHeightData, windowTop, bs.opts.CLOSEST_HIGHER);
}
```

Consequently, `undefined` value of `displayIndexStart` will trigger the  return of function `getTopSpacerHeight` to be `undefined` too.

```
getTopSpacerHeight(displayIndexStart) {
    var previous = displayIndexStart - 1;
    return previous < 0 ? 0 : this.prefixHeightData[previous];
}
```

I have not tested the above case, it's just a logical deduction.

**Comment by garetht** [comment]
@jimmykobe1171 Yup, you're right about that. I happened to bump into this when performing some typechecks. Hopefully that will prevent this from occurring in the future.
