### ISSUE TITLE
dynamic containerHeight?

### ISSUE THREAD

**Issue by vgoklani** [seatgeek/react-infinite#71]
How would I dynamically set the containerHeight in this:

		return React.createElement(Infinite, {
				elementHeight: 100,
				containerHeight: 1200,
				infiniteLoadBeginBottomOffset: 200,
				handleScroll: this.handleScroll,
				onInfiniteLoad: this.handleInfiniteLoad,
				loadingSpinnerDelegate: this.elementInfiniteLoad(),
				isInfiniteLoading: this.state.isInfiniteLoading,
				timeScrollStateLastsForAfterUserScrolls: 1000,
				className: "scroller"
				}, elements);

I would like to set it based on the page size

**Comment by garetht** [comment]
The function that calls `React.createElement` would compute the appropriate `containerHeight` with a function based on something like `window.innerHeight`. It can also listen for changes and feed `react-infinite` the appropriate new height.
