### ISSUE TITLE
How to efficiently calculate the height between text boxes?

### ISSUE THREAD

**Issue by vgoklani** [seatgeek/react-infinite#72]
I'm using your library for a highly curated twitter feed, and I've found that the "heights" [or more precisely the separation between the text boxes] is a function of both the number of characters in the message (I've limited them to 140), which directly affects the number of lines being used, the way the text gets wrapped, which depends on the spacing, and the output device (i.e. the resolution of the screen, iPhone 5, vs 6, vs 6+). I'm curious, there are a lot of different cases here, is there a simple way of solving this problem? My approach involves lots of "if" statements, and it's just a hack. It's tricky since the width of the box is constantly changing...

**Comment by garetht** [comment]
There is an open issue here https://github.com/seatgeek/react-infinite/issues/61 discussing automatic measurement of variable height list elements, and is not yet implemented. But for now, React Infinite will continue to work for any height greater than or equal to the actual height of the rendered element. So if you had an upper bound for each element, or several upper bounds calibrated by some heuristics about text length, this would work. This may be more inefficient, but barring some edge case the inefficiency should be a constant that does not scale with the length of the list.
