### ISSUE TITLE
Inconsistent onInfiniteLoad() calls

### ISSUE THREAD

**Issue by mislagle** [seatgeek/react-infinite#73]
It's like react-infinite never realizes that it has hit the bottom of the list. The onInfiniteLoad() inconsistently fires. Sometimes it isn't called, sometimes it is called once, but it is NEVER called more than once.

Anyone else having this issue or think they may know what is wrong? I've messed with the props and left them as defaults and nothing works.

**Comment by garetht** [comment]
`onInfiniteLoad` is certainly called more than once in the examples. Do you have some sample code?
