### ISSUE TITLE
getDOMNode on refs has been deprecated in React v0.14

### ISSUE THREAD

**Issue by nason** [seatgeek/react-infinite#79]
See http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#new-deprecations-introduced-with-a-warning for details.

Running an app with a react-infinite component logs the following warning:
> Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Infinite`.

**Comment by garetht** [comment]
We're using `React.findDOMNode` for now to maintain compatibility with 0.13 but we'll switch to directly getting the node from the refs in a release soon.

**Comment by vgoklani** [comment]
Thanks @garetht, it's awesome to see all these updates!

**Comment by palmdeezy** [comment]
what's the status of this update?

**Comment by bobiblazeski** [comment]
Any update of this

**Comment by garetht** [comment]
Will look at this later in the week.

**Comment by garetht** [comment]
Available in 0.7.1

**Comment by doubledherin** [comment]
Is 0.7.1 still in the works?
