### ISSUE TITLE
`getTopSpacerHeight` is incorrectly computing the div height

### ISSUE THREAD

**Issue by eudisd** [seatgeek/react-infinite#80]
It seems that consistently, the `getTopSpacerHeight` is not calculating the top spacer height at the boundary: 

```javascript
  var previous = displayIndexStart - 1;
  return previous < 0 ? 0 : this.prefixHeightData[previous];
```

Not sure if this is an off by one error when getting the index of the prefixHeightData or if the height data is just not calculated correctly to begin with.

I have a list of 45 `<li>` elements, all of equal height `[53, 53, 53...] ` and a scrollHeight of `993`, both set on the `Infinite` component.  Each `<li>` has a number denoting it's sequential position. ie `<li>1</li><li>2</li>...` When I scroll the components at the boundary of calculating this height, the numbers skip an `<li>` and start one after this position, which is completely wrong and destroys the impression of a smooth scroll.  In other words, if at the top of the scrollable container, I see the `<li>` with the number 25 say, as soon as the bottom of that `<li>` element I see the like with the number 23 instead of 24, at the very top of the scrollable div.

**Comment by garetht** [comment]
I'm going to guess it's an off-by-one error. I'll investigate further soon.

**Comment by eudisd** [comment]
Sounds good.

You can see the problem somewhat, although to a lesser extent in the first example here: 
http://chairnerd.seatgeek.com/react-infinite-a-browser-ready-efficient-scrolling-container-based-on-uitableview/

You will see that if you scroll slowly, at the end of the `List Item 13` div the issue appears.

**Comment by garetht** [comment]
@eudisd Good catch with the example. I took a look at it and realized the jerkiness there occurs because the `elementHeight`s were specified to be 40px while they were actually 50px in the DOM. I recreated the 45 `li`s and cannot reproduce this. Are you sure the `li` elements are all 53px in the DOM?

Do you see anything in the examples that show this problem? If it persists, can you paste some sample code?

**Comment by eudisd** [comment]
@garetht I will try to isolate the problem I see in my project and post a gist later tonigh

**Comment by garetht** [comment]
Assuming that this is no longer an issue.
