### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollable' of undefined

### ISSUE THREAD

**Issue by LXQLab** [seatgeek/react-infinite#88]
program break at 
utilities.getScrollTop = function () {
        var scrollable = React.findDOMNode(_this.refs.scrollable);  // exception
        return scrollable ? scrollable.scrollTop : 0;
      };

break stack like:
    React.createClass.generateComputedUtilityFunctions.utilities.getScrollTop
    recomputeInternalStateFromProps	
    getInitialState
    Constructor
    ReactCompositeComponentMixin.mountComponent
    wrapper
    ....

**Comment by garetht** [comment]
0.5.6 now checks for `this.refs` and `this.refs.scrollable`.

**Comment by shahbhavir** [comment]
@garetht Can you also update bower package ?

**Comment by garetht** [comment]
@shahbhavir Done.

**Comment by shahbhavir** [comment]
@garetht Thank you.
