### ISSUE TITLE
require File name is Error

### ISSUE THREAD

**Issue by LXQLab** [seatgeek/react-infinite#91]
When use gulp in linux, these codes will fail:
  var ConstantInfiniteComputer = require('../computers/constantInfiniteComputer.js');
  var ArrayInfiniteComputer = require('../computers/arrayInfiniteComputer.js');

Reason: First character of file name is uppercase，there are ConstantInfiniteComputer.js, ArrayInfiniteComputer.js

**Comment by garetht** [comment]
@LXQLab The file name is lowercase: https://github.com/seatgeek/react-infinite/blob/master/src/computers/arrayInfiniteComputer.js

**Comment by LXQLab** [comment]
After 'npm install react-infinite --save', there are node_modules/react-infinite/build/computer/ArrayInfiniteComputer.js. I don't know why files in build has diffirent names.

![image](https://cloud.githubusercontent.com/assets/15071470/10583214/5e67eb82-76be-11e5-94d4-a9405096eb89.png)

**Comment by garetht** [comment]
Ah got it. Just rebuilt `/build` with 0.5.7. Sorry about that!
