### ISSUE TITLE
How to make infinity scroll for nested structures?

### ISSUE THREAD

**Issue by stepancar** [seatgeek/react-infinite#94]
Hello! Thank you for this great project.
I faced with problem. I need create selector with grouped items.
For example, 20 groups, each group have 100-200 items.
In this case we need consieder each node as rendered item and filter.
May be anybody faced with the same problem, or, maybe author of this awesome project can provide simple solution?
Thank you!

**Comment by garetht** [comment]
I believe multiple React Infinites will work fine, like this, if not used on the window, but certainly let me know if there are any problems:

```jsx
<div>
  <Infinite elementHeight={10} containerHeight={100}>
    <div/>
    <div/>
  </Infinite>
  <Infinite elementHeight={10} containerHeight={100}>
    <div/>
    <div/>
  </Infinite>
</div>
```

**Comment by stepancar** [comment]
@garetht, thank you for your answer, but i need somthing like ![](http://i.imgur.com/MZt1Ezl.png)
it should be one list, where items groupped. each group can include many many items.

**Comment by stepancar** [comment]
we can just represents nested structure as linear.
