### ISSUE TITLE
How to use custom scroller in react-infinite?

### ISSUE THREAD

**Issue by stepancar** [seatgeek/react-infinite#95]
How to use custom scroller? Not all browser support styles for scroller like chrome. May be it reason to include custom scroller to this package?

**Comment by garetht** [comment]
Unfortunately, providing custom scrollbars is out of the scope of this project. It should be possible to use the `handleScroll` listener to get the data necessary to attach your own if absolutely required.

**Comment by stepancar** [comment]
@garetht, handleScroll is just listener which called when dom onScroll event happens. There is no way to use custom scroller, which need if you want to customize css, or use multitouch events on scroller, and list of data. 
Ok, i agree with you, that its out of the scope of this project.
Thank you!
